### ISSUE TITLE
Begin to integrate Nutch REST services

### ISSUE THREAD

**Issue by chrismattmann** [ContinuumIO/nutchpy#12]
we should start to integrate NUTCH's new REST API:

https://wiki.apache.org/nutch/Nutch_1.X_RESTAPI

The same way that I did this with [Tika-Python](http://github.com/chrismattmann/tika-python/).

**Comment by sujen1412** [comment]
I am working on porting the sequence reader app to a REST API in Nutch, please find the API documentation at http://docs.nutchpytonutchrestapi.apiary.io/ and give your feedbacks. 

Thank you :)

**Comment by ahmadia** [comment]
Excellent.  We need access to:

* reconfigure the Nutch RegEx parser
* dump images to a location (previous Memex Explorer functionality?)
* dump common crawl (another Memex Explorer function?)

**Comment by lewismc** [comment]
Good job soliciting feedback on this Sujen and showing initiative to make
it easy for others to contribute to the conversation.

On Thursday, October 22, 2015, Sujen Shah <notifications@github.com> wrote:

> I am working on porting the sequence reader app to a REST API in Nutch,
> please find the API documentation at
> http://docs.nutchpytonutchrestapi.apiary.io/ and give your feedbacks.
>
> Thank you :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuumIO/nutchpy/issues/12#issuecomment-150373047>.
>


-- 
*Lewis*

**Comment by chrismattmann** [comment]
@sujen1412 looks great. Can you open up an issue in https://github.com/chrismattmann/nutch-python and ref it here?

**Comment by chrismattmann** [comment]
please proceed @sujen1412 this looks good.

**Comment by chrismattmann** [comment]
taken care of in https://github.com/chrismattmann/nutch-python/issues/12
