### ISSUE TITLE
JVM gateway process remains alive even after the termination of python's reader process

### ISSUE THREAD

**Issue by thammegowda** [ContinuumIO/nutchpy#19]
### Request : 
Auto shutdown gateway process when the python process exits.

### How to reproduce:
Run sequence_reader examples few times and then inspect the processes list.
![nutchpy_gateway](https://cloud.githubusercontent.com/assets/1865964/10121502/c362fab8-64a3-11e5-9106-91ecce8d8447.png)

**Comment by chrismattmann** [comment]
thanks for this report..can you add a Pull Request that kills it on stop?

**Comment by chrismattmann** [comment]
@thammegowda

**Comment by thammegowda** [comment]
@chrismattmann  Added  #24,  using garbage collection hook on gateway object  to auto invoke shutdown procedure.
