### ISSUE TITLE
conda install apache-maven / nutchpy with blaze doesn't work with linux 32-bit versions

### ISSUE THREAD

**Issue by preshathakkar** [ContinuumIO/nutchpy#23]
I am constantly facing an error if I try to install any apache-maven or nutchpy with the help of conda in Ubuntu 12.04 : 32-bit version. Also, I tried to see if anaconda had any version of nutchpy compatible with 32-bit versions, but didn't find any.

presha@presha-Inspiron-N5110:~/IR$ conda install -c blaze apache-maven
Fetching package metadata: ......
Error: No packages found in current linux-32 channels matching: apache-maven

You can search for this package on anaconda.org with

    anaconda search -t conda apache-maven
presha@presha-Inspiron-N5110:~/IR$ conda install -c blaze nutchpy
Fetching package metadata: ......
Error: No packages found in current linux-32 channels matching: nutchpy

You can search for this package on anaconda.org with

    anaconda search -t conda nutchpy
presha@presha-Inspiron-N5110:~/IR$ anaconda search -t conda nutchpy
Using binstar api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     blaze/nutchpy             |      0.1 | conda           | linux-64, win-64, osx-64
Found 1 packages

Could someone please suggest an alternative approach to install it in ubuntu 12.04, 32 bit version.

**Comment by chrismattmann** [comment]
can you install ubuntu 64-bit? @preshathakkar

**Comment by preshathakkar** [comment]
I have all the things setup on ubuntu 32-bit for about 2 years. And I would have to install it from scratch. I cannot make changes in the current installation. If you could suggest a work around, I could do that.

**Comment by thammegowda** [comment]
@preshathakkar Assuming you already have setup 32-bit JDK, you can try installing maven with `sudo apt-get install maven`. 
Warning: Some libraries may be missing for 32-bit! So, upgrading is recommended.

**Comment by preshathakkar** [comment]
@thammegowda I have already installed maven with apt-get. But it doesn't seem to work

**Comment by chrismattmann** [comment]
@preshathakkar can you use http://conda.pydata.org/docs/commands/build/conda-convert.html ?

**Comment by preshathakkar** [comment]
@chrismattmann I tried converting nutchpy package from blaze to linux 32 bit, It got converted but while installing it faces an error in py4j. For that I converted py4j package from blaze and installed it. After installing I tried to install nutchpy, but it still shows the same error.

I also tried to convert apache-maven, but it shows an error while converting. I posted the issue in conda for the same.

Could you let me know if I could change the nutchpy installation in such a way that it accepts the py4j which I installled by converting. By this I can pass through the current error and know if the converted version works or not.

**Comment by chrismattmann** [comment]
Go for it

**Comment by chrismattmann** [comment]
no time to work on this
